openapi: 3.0.0
info:
  title: Product Search API
  description: "REST endpoint that provides Search and Filter capability over the usersearchs info."
  version: '1.0'
tags:
  - name: Search
    description: Search usersearch using searchTerm and filters
  - name: Reindex
    description: Baseline your search index with source
paths:
  /users/v1/searches:
    get:
      description: |
        Search for usersearch information from a search index using keyword search and filters.
      tags:
        - Search
      parameters:
        - name: search
          description: The phrase for keyword search happen
          in: query
          required: false
          example: 'samsung'
          schema:
            type: string
        - name: minPrice
          description: Minimum price range filter
          in: query
          required: false
          example: 10
          schema:
            type: integer
        - name: maxPrice
          description: Maximum price range filter
          in: query
          required: false
          example: 10
          schema:
            type: integer
        - name: minReviewRating
          description: Minimum review rating range filter
          in: query
          required: false
          example: 2
          schema:
            type: integer
        - name: maxReviewRating
          description: Maximum review rating range filter
          in: query
          required: false
          example: 4
          schema:
            type: integer
        - name: minReviewCount
          description: Minimum review count range filter
          in: query
          required: false
          example: 10
          schema:
            type: integer
        - name: maxReviewCount
          description: Maximum review rating range filter
          in: query
          required: false
          example: 100
          schema:
            type: integer
        - name: inStock
          description: The phrase against whick keyword search will happen
          in: query
          required: false
          example: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResponseProductSearch'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResponseError400'
  /users/v1/reindex:
    post:
      description: |
        Reindex for loading/reloading usersearch information from http source
      tags:
        - Reindex
      responses:
        '202':
          description: ACCEPTED
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResponseReindex'
components:
  schemas:
    ResponseProductSearch:
      description: Product search response
      type: object
      properties:
        usersearchs:
          type: array
          items:
            type: object
            properties:
              usersearchId:
                type: string
                example: "1112121212"
              usersearchName:
                type: string
                example: "samsung 1312"
              shortDescription:
                type: string
                example: "UHD TV latest"
              longDescription:
                type: string
                example: "A very nice TV latest."
              usersearchImage:
                type: string
                example: "/image/server/1.jpg"
              reviewRating:
                type: number
                example: 1.1
              reviewCount:
                type: integer
                example: 100
              inStock:
                type: boolean
              price:
                type: string
                example: "$100,00.00"
        totalProducts:
          type: integer
          example: 12
        pageNumber:
          type: integer
          example: 1
        pageSize:
          type: integer
          example: 30
        statusCode:
          type: integer
          example: 200
    ResponseReindex:
      description: Product reindex response
      type: object
      properties:
        totalInIndex:
          type: integer
          example: 122
        totalAtSource:
          type: integer
          example: 122
    ResponseError400:
      description: A response body envelope with error codes and descriptions that may occur during the update operation.
      type: object



