version: '3'
services:
  web:
    image: 'usersearch:latest'
    ports:
      - "8080:8080"
      - "5005:5005"
      - "8077"
    networks:
      - mynetwork
    environment:
#      - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
      - "HOST_IP=host.docker.internal"
#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
#    container_name: elasticsearch
#    environment:
#      - cluster.name=usersearch-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - mynetwork
#  redisdb:
#    image: "redis:alpine"
#    hostname: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - mynetwork
networks:
  mynetwork:
#volumes:
##  esdata:
##    driver: local